#!/usr/bin/env python3
"""
Daily Digest Automation — Template

Pulls Granola meeting notes, generates an AI-powered digest tailored to your
writing style and interests, and delivers it by email with a published web archive.

Configure via:
  config/writing_guide.md   — writing style and output format
  config/filter_config.json — companies, geographies, sectors, people you care about
  ~/.daily_digest/config.json — API keys, email settings, and Granola options (created by setup.py)
"""

import argparse
import os
import json
import anthropic
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import List, Dict, Optional
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
CONFIG_FILE = Path.home() / ".daily_digest" / "config.json"
ARCHIVE_DIR = Path.home() / ".daily_digest" / "archive"

# Load user config files from repo
REPO_DIR = Path(__file__).parent
WRITING_GUIDE_FILE = REPO_DIR / "config" / "writing_guide.md"
FILTER_CONFIG_FILE = REPO_DIR / "config" / "filter_config.json"


# ---------------------------------------------------------------------------
# Email HTML template
# ---------------------------------------------------------------------------
EMAIL_HTML_TEMPLATE = '''<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; line-height: 1.7; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
    h1 {{ color: #1a1a1a; border-bottom: 2px solid #e1e4e8; padding-bottom: 10px; margin-bottom: 20px; }}
    h2 {{ color: #24292e; margin-top: 40px; margin-bottom: 16px; border-bottom: 2px solid #888; padding-bottom: 8px; font-size: 1.3em; text-transform: uppercase; letter-spacing: 0.5px; }}
    h3 {{ color: #24292e; margin-top: 28px; margin-bottom: 12px; border-bottom: 1px solid #e1e4e8; padding-bottom: 6px; font-size: 1.1em; }}
    p {{ margin-bottom: 14px; }}
    ul {{ padding-left: 20px; margin-bottom: 16px; }}
    li {{ margin: 16px 0; padding-bottom: 4px; }}
    .header {{ background-color: #f6f8fa; padding: 15px; border-radius: 6px; margin-bottom: 20px; }}
    .citations {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e1e4e8; }}
    .citations h3 {{ color: #586069; font-size: 0.95em; }}
    .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e1e4e8; color: #586069; font-size: 0.9em; }}
    strong {{ color: #24292e; }}
    a {{ color: #0366d6; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
  </style>
</head>
<body>
  <div class="header">
    <h1>{digest_name}</h1>
    <p><strong>Date:</strong> {date}{meeting_badge}</p>
  </div>
  {content}
  <div class="footer">
    <p>Generated by Daily Digest automation</p>
  </div>
</body>
</html>'''


# ---------------------------------------------------------------------------
# Granola meeting notes client
# ---------------------------------------------------------------------------

class GranolaClient:
    """
    Fetches today's meeting notes from Granola using its (reverse-engineered)
    private API. Credentials are read from the Granola desktop app's local
    credential store — no separate login required if you're already signed in.

    Credential file locations:
      macOS:   ~/Library/Application Support/Granola/supabase.json
      Windows: %APPDATA%\\Granola\\supabase.json

    The file is written by the Granola app and contains a WorkOS access_token
    and refresh_token. This client refreshes the token automatically when
    it expires (tokens rotate on every refresh — the new token is written
    back to disk immediately).
    """

    GRANOLA_API_BASE = "https://api.granola.ai"
    WORKOS_AUTH_URL = "https://api.workos.com/user_management/authenticate"

    # WorkOS client ID used by the Granola desktop app (from reverse engineering).
    # This is the public identifier for Granola's OAuth application — it is not
    # a secret and appears in every Granola API request.
    GRANOLA_CLIENT_ID = "client_01JKGE7Y2BPGKZA9S0XM1G9AMF"

    def __init__(self, credentials_path: Optional[Path] = None):
        if credentials_path:
            self.credentials_path = Path(credentials_path)
        else:
            self.credentials_path = self._default_credentials_path()

        self.credentials = self._load_credentials()
        self.session = requests.Session()
        self.session.headers.update({
            "Content-Type": "application/json",
            "User-Agent": "Granola/5.354.0",
            "X-Client-Version": "5.354.0",
        })
        self._ensure_valid_token()

    @staticmethod
    def _default_credentials_path() -> Path:
        import platform
        if platform.system() == "Windows":
            return Path(os.environ.get("APPDATA", "")) / "Granola" / "supabase.json"
        return Path.home() / "Library" / "Application Support" / "Granola" / "supabase.json"

    def _load_credentials(self) -> Dict:
        if not self.credentials_path.exists():
            raise FileNotFoundError(
                f"Granola credentials not found at {self.credentials_path}. "
                "Make sure Granola is installed and you are signed in."
            )
        with open(self.credentials_path) as f:
            return json.load(f)

    def _ensure_valid_token(self) -> None:
        """Refresh the WorkOS access token using the stored refresh token.
        Granola uses rotating refresh tokens — we must write the new token
        back to disk immediately or subsequent refreshes will fail."""
        refresh_token = self.credentials.get("refresh_token")
        if not refresh_token:
            return  # No refresh token; use access_token as-is and hope it's valid.

        try:
            resp = requests.post(
                self.WORKOS_AUTH_URL,
                json={
                    "client_id": self.GRANOLA_CLIENT_ID,
                    "grant_type": "refresh_token",
                    "refresh_token": refresh_token,
                },
                timeout=30,
            )
            resp.raise_for_status()
            data = resp.json()

            self.credentials["access_token"] = data["access_token"]
            self.credentials["refresh_token"] = data["refresh_token"]

            # Write rotated tokens back so the next run (and Granola itself) can use them.
            with open(self.credentials_path, "w") as f:
                json.dump(self.credentials, f, indent=2)

        except Exception as e:
            print(f"  Warning: Could not refresh Granola token ({e}). Using cached access token.")

    def _auth_header(self) -> Dict:
        return {"Authorization": f"Bearer {self.credentials.get('access_token', '')}"}

    # ------------------------------------------------------------------
    # Fetch meetings
    # ------------------------------------------------------------------

    def get_recent_meetings(self) -> List[Dict]:
        """Return meeting summaries from the last 7 days."""
        from dateutil import parser as date_parser

        print("  Fetching this week's Granola meeting notes...")
        cutoff = datetime.now(timezone.utc) - timedelta(days=7)
        meetings: List[Dict] = []

        try:
            resp = self.session.post(
                f"{self.GRANOLA_API_BASE}/v2/get-documents",
                headers=self._auth_header(),
                json={"limit": 50, "offset": 0, "include_last_viewed_panel": True},
                timeout=30,
            )
            resp.raise_for_status()
            raw = resp.json()

            # The response may be a list or {"documents": [...]}
            docs = raw if isinstance(raw, list) else raw.get("documents", [])

            for doc in docs:
                doc_date = None
                for field in ("created_at", "updated_at"):
                    raw_date = doc.get(field)
                    if raw_date:
                        try:
                            doc_date = date_parser.parse(raw_date)
                            if doc_date.tzinfo is None:
                                doc_date = doc_date.replace(tzinfo=timezone.utc)
                            break
                        except Exception:
                            continue

                if doc_date is None or doc_date >= cutoff:
                    meetings.append(self.extract_meeting_summary(doc))

        except Exception as e:
            print(f"  Error fetching Granola meetings: {e}")

        print(f"  Found {len(meetings)} Granola meetings from the last 7 days")
        return meetings

    # ------------------------------------------------------------------
    # Content extraction
    # ------------------------------------------------------------------

    def extract_meeting_summary(self, doc: Dict) -> Dict:
        """Return a clean dict summarising one Granola document."""
        panel = doc.get("last_viewed_panel") or {}
        content_node = panel.get("content") or {}
        notes = self._prosemirror_to_markdown(content_node).strip()

        return {
            "id": doc.get("id", ""),
            "title": doc.get("title", "Untitled Meeting"),
            "date": doc.get("created_at", ""),
            "notes": notes[:4000],  # Guard against very long transcripts
        }

    @classmethod
    def _prosemirror_to_markdown(cls, node: Dict, _depth: int = 0) -> str:
        """Recursively convert a ProseMirror JSON node tree to Markdown text."""
        if not node:
            return ""

        node_type = node.get("type", "")
        children = node.get("content", [])

        if node_type == "text":
            return node.get("text", "")

        if node_type == "hardBreak":
            return "\n"

        if node_type == "heading":
            level = node.get("attrs", {}).get("level", 2)
            inner = "".join(cls._prosemirror_to_markdown(c) for c in children)
            return f"{'#' * level} {inner}\n\n"

        if node_type == "paragraph":
            inner = "".join(cls._prosemirror_to_markdown(c) for c in children)
            return f"{inner}\n\n" if inner.strip() else ""

        if node_type in ("bulletList", "orderedList"):
            return "".join(cls._prosemirror_to_markdown(c, _depth) for c in children)

        if node_type == "listItem":
            inner = "".join(cls._prosemirror_to_markdown(c, _depth + 1) for c in children).strip()
            indent = "  " * _depth
            return f"{indent}- {inner}\n"

        # Fallback: recurse into children
        return "".join(cls._prosemirror_to_markdown(c, _depth) for c in children)


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------

class DailyDigest:
    def __init__(self):
        self.config = self._load_config()
        self.anthropic_api_key = self.config.get("anthropic_api_key")
        self.email_config = self.config.get("email", {})

        ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)

        self.anthropic_client = anthropic.Anthropic(api_key=self.anthropic_api_key)

        # Load writing guide and filter config
        self.writing_guide = self._load_writing_guide()
        self.filter_config = self._load_filter_config()

        # Granola integration (optional — gracefully disabled if not configured)
        self.granola_client: Optional[GranolaClient] = self._init_granola()

    # ------------------------------------------------------------------
    # Config loading
    # ------------------------------------------------------------------

    def _load_config(self) -> Dict:
        if not CONFIG_FILE.exists():
            raise FileNotFoundError(
                f"Config not found at {CONFIG_FILE}. Run: python3 setup.py"
            )
        with open(CONFIG_FILE) as f:
            return json.load(f)

    def _load_writing_guide(self) -> str:
        if WRITING_GUIDE_FILE.exists():
            return WRITING_GUIDE_FILE.read_text()
        return "Write clearly, concisely, and analytically. Use specific numbers over vague adjectives."

    def _load_filter_config(self) -> Dict:
        if FILTER_CONFIG_FILE.exists():
            with open(FILTER_CONFIG_FILE) as f:
                return json.load(f)
        return {}

    def _init_granola(self) -> Optional[GranolaClient]:
        """Return a GranolaClient if Granola is enabled and credentials are found."""
        granola_cfg = self.config.get("granola", {})

        # Explicit opt-out in config
        if granola_cfg.get("enabled") is False:
            return None

        credentials_path = granola_cfg.get("credentials_path")
        cred_path = Path(credentials_path) if credentials_path else GranolaClient._default_credentials_path()

        if not cred_path.exists():
            return None  # Granola not installed / not signed in — skip silently

        try:
            print("Granola credentials found — meeting notes will be included in today's digest.")
            return GranolaClient(credentials_path=cred_path)
        except Exception as e:
            print(f"Warning: Could not initialise Granola client ({e}). Continuing without meeting notes.")
            return None

    # ------------------------------------------------------------------
    # Prompt construction
    # ------------------------------------------------------------------

    def _build_filter_context(self) -> str:
        """Convert filter_config into a structured context block for the prompt."""
        fc = self.filter_config
        lines = []

        digest_name = fc.get("digest_name", "My Digest")
        author = fc.get("author_name", "the reader")
        focus = fc.get("focus_description", "")
        lines.append(f"DIGEST: {digest_name}")
        lines.append(f"AUTHOR: {author}")
        if focus:
            lines.append(f"FOCUS: {focus}")
        lines.append("")

        # Portfolio companies
        companies = fc.get("portfolio_companies", [])
        if companies:
            lines.append("PORTFOLIO / KEY ENTITIES:")
            for c in companies:
                if c.get("name") and c["name"] != "Company Name":
                    desc = c.get("description", "")
                    kw = ", ".join(c.get("keywords", []))
                    lines.append(f"  • {c['name']}: {desc} [keywords: {kw}]")
            lines.append("")

        # Geographies
        geos = fc.get("geographies", [])
        if geos:
            lines.append("GEOGRAPHIES OF INTEREST:")
            for g in geos:
                if g.get("name"):
                    kw = ", ".join(g.get("keywords", []))
                    lines.append(f"  • {g['name']}: {g.get('why_relevant','')} [keywords: {kw}]")
            lines.append("")

        # Industries
        industries = fc.get("industries_sectors", [])
        if industries:
            lines.append("INDUSTRIES / SECTORS OF INTEREST:")
            for i in industries:
                if i.get("name"):
                    kw = ", ".join(i.get("keywords", []))
                    lines.append(f"  • {i['name']}: {i.get('why_relevant','')} [keywords: {kw}]")
            lines.append("")

        # Themes
        themes = fc.get("themes", [])
        if themes:
            lines.append("MACRO THEMES:")
            for t in themes:
                if t.get("name"):
                    kw = ", ".join(t.get("keywords", []))
                    lines.append(f"  • {t['name']}: {t.get('why_relevant','')} [keywords: {kw}]")
            lines.append("")

        # People
        people = fc.get("people", [])
        if people:
            lines.append("PEOPLE TO TRACK:")
            for p in people:
                if p.get("name"):
                    lines.append(f"  • {p['name']} ({p.get('role','')}): {p.get('why_relevant','')}")
            lines.append("")

        return "\n".join(lines)

    def _build_section_template(self, has_meetings: bool = False) -> str:
        """Build section instructions from writing_guide.md."""
        fc = self.filter_config
        digest_name = fc.get("digest_name", "My Digest")

        has_companies = bool([
            c for c in fc.get("portfolio_companies", [])
            if c.get("name") and c["name"] != "Company Name"
        ])

        meetings_section = ""
        if has_meetings:
            meetings_section = """
<h2>Weekly Granola Summary</h2>
Summarise each meeting from the Granola notes above. For each:
1. <strong>Meeting title + date/time</strong>
2. <ul><li> Key decisions made (bold the decision)
3. <ul><li> Open action items — who owns what (bold the owner and the task)
4. <ul><li> Connections to today's articles or broader themes in this digest — only include if the link is direct and non-obvious.
Keep each meeting tight: decisions and actions only, no meeting-room filler.
"""

        sections = f"""
OUTPUT SECTIONS (use HTML formatting for email):

{meetings_section}
<h2>Other Sections</h2>
Include any additional sections defined in the writing guide that have relevant content. Skip sections with no relevant content and state why briefly.
"""
        return sections

    # ------------------------------------------------------------------
    # Generation
    # ------------------------------------------------------------------

    def generate_synopsis(self, historical: List[Dict], meetings: Optional[List[Dict]] = None) -> Dict:
        """Generate AI digest using Claude."""
        print("Generating digest with Claude...")

        today = datetime.now()
        is_weekly_day = today.weekday() == 0  # Monday

        # Historical context
        historical_summary = ""
        if historical:
            historical_summary = "PREVIOUS SYNOPSES (last 7 days — for pattern continuity, not repetition):\n\n"
            for i, h in enumerate(historical, 1):
                themes = h.get("key_themes", [])
                historical_summary += f"  Day -{i} ({h.get('date','')}): {', '.join(themes[:3])}\n"

        # Weekly section
        weekly_section = ""
        if is_weekly_day:
            weekly_section = """
<h2>Weekly Pattern Analysis</h2>
Synthesize the FULL WEEK — not just today. Draw from the historical synopses. Do NOT repeat insights already covered in today's daily sections.

Identify 3 patterns from this week that represent structural changes, not cyclical noise. Each: bold title → 3-5 bullets with specific data points → the hard questions that remain open.

What changed this week that matters in 5 years?
"""

        filter_context = self._build_filter_context()
        section_template = self._build_section_template(has_meetings=bool(meetings))

        # Build meeting notes block
        meetings_block = ""
        if meetings:
            meeting_lines = [f"THIS WEEK'S GRANOLA MEETING NOTES ({len(meetings)} meeting(s)):\n"]
            for m in meetings:
                meeting_lines.append(f"--- Meeting: {m['title']} ({m['date']}) ---")
                meeting_lines.append(m["notes"] or "(no notes captured)")
                meeting_lines.append("")
            meetings_block = "\n".join(meeting_lines)

        prompt = f"""You are generating a personalized weekly meeting digest.

{filter_context}

WRITING GUIDE:
{self.writing_guide}

Today's date: {today.strftime('%Y-%m-%d')}

{meetings_block}

{historical_summary}

{section_template}

{weekly_section}

CRITICAL RULES:
- Each insight appears ONCE in the most relevant section. Do not restate across sections.
- Bold all key numbers (<strong>42%</strong>) and entity names (<strong>Company Name</strong>).
- Numbers over adjectives — every vague claim earns its place with evidence.
- Assume the reader has deep domain knowledge. Skip basics.
- Use generous HTML spacing between elements.
"""

        try:
            message = self.anthropic_client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=8000,
                messages=[{"role": "user", "content": prompt}],
            )
            synopsis_text = message.content[0].text
        except Exception as e:
            print(f"Error generating synopsis: {e}")
            synopsis_text = f"Error generating synopsis: {e}"

        return {
            "date": today.strftime("%Y-%m-%d"),
            "meeting_count": len(meetings) if meetings else 0,
            "synopsis": synopsis_text,
            "key_themes": self._extract_themes(synopsis_text),
            "is_weekly_report": is_weekly_day,
        }

    def _extract_themes(self, synopsis_text: str) -> List[str]:
        themes = []
        for line in synopsis_text.split("\n"):
            line = line.strip()
            if line.startswith(("-", "•")):
                theme = line.lstrip("-•").strip().split(".")[0][:50]
                if theme:
                    themes.append(theme)
            elif line.startswith("**") and line.endswith("**"):
                theme = line.strip("*").strip()[:50]
                if theme:
                    themes.append(theme)
        return themes[:5]

    # ------------------------------------------------------------------
    # Archive
    # ------------------------------------------------------------------

    def get_historical_synopses(self, days: int = 7) -> List[Dict]:
        historical = []
        for i in range(1, days + 1):
            date = datetime.now() - timedelta(days=i)
            filename = ARCHIVE_DIR / f"synopsis_{date.strftime('%Y%m%d')}.json"
            if filename.exists():
                with open(filename) as f:
                    historical.append(json.load(f))
        return historical

    def save_synopsis(self, synopsis: Dict) -> None:
        today = datetime.now()
        filename = ARCHIVE_DIR / f"synopsis_{today.strftime('%Y%m%d')}.json"
        with open(filename, "w") as f:
            json.dump(synopsis, f, indent=2)
        print(f"Archived to {filename}")

    # ------------------------------------------------------------------
    # Site update
    # ------------------------------------------------------------------

    def update_site_data(self) -> None:
        """Rebuild digests.json, commit, and push to trigger Netlify deploy."""
        import subprocess

        print("Updating site data...")
        from build_site import load_synopses, build_digests_json

        synopses = load_synopses(ARCHIVE_DIR)
        if not synopses:
            print("No synopses found. Skipping site update.")
            return

        output_dir = REPO_DIR / "site" / "data"
        build_digests_json(synopses, output_dir)

        commit_msg = f"Update digest data — {datetime.now().strftime('%Y-%m-%d')}"
        try:
            subprocess.run(["git", "add", "site/data/digests.json"], cwd=REPO_DIR, check=True, capture_output=True)
            result = subprocess.run(["git", "diff", "--cached", "--quiet"], cwd=REPO_DIR, capture_output=True)
            if result.returncode == 0:
                print("No changes. Skipping push.")
                return
            subprocess.run(["git", "commit", "-m", commit_msg], cwd=REPO_DIR, check=True, capture_output=True)
            subprocess.run(["git", "push", "origin", "main"], cwd=REPO_DIR, check=True, capture_output=True, timeout=60)
            print("Pushed to GitHub. Netlify will auto-deploy.")
        except subprocess.CalledProcessError as e:
            print(f"Git error: {e.stderr[:300] if e.stderr else e}")
        except subprocess.TimeoutExpired:
            print("Git push timed out.")

    # ------------------------------------------------------------------
    # Email
    # ------------------------------------------------------------------

    def send_email(self, synopsis: Dict) -> None:
        print("Sending email...")

        digest_name = self.filter_config.get("digest_name", "Daily Digest")
        subject = f"{digest_name} — {synopsis['date']}"
        if synopsis.get("is_weekly_report"):
            subject = f"{digest_name} — Weekly Analysis — {synopsis['date']}"

        meeting_count = synopsis.get("meeting_count", 0)
        meeting_badge = f" | <strong>Meetings:</strong> {meeting_count}" if meeting_count else ""

        html_body = EMAIL_HTML_TEMPLATE.format(
            digest_name=digest_name,
            date=synopsis["date"],
            meeting_badge=meeting_badge,
            content=synopsis["synopsis"],
            citation_count=len(citations),
            citations="\n".join(citations) if citations else "<li>No articles</li>",
        )

        plain_text = (
            f"{digest_name} — {synopsis['date']}\n"
            f"Articles: {synopsis['document_count']} | Priority: {synopsis['priority_count']}\n\n"
            f"{synopsis['synopsis']}\n\n---\nGenerated by Daily Digest automation"
        )

        smtp_server = self.email_config.get("smtp_server", "smtp.gmail.com")
        smtp_port = self.email_config.get("smtp_port", 587)
        sender_email = self.email_config.get("sender_email")
        sender_password = self.email_config.get("sender_password")
        recipient_email = self.email_config.get("recipient_email")

        if not all([sender_email, sender_password, recipient_email]):
            print("Email config incomplete. Skipping send. Synopsis saved to archive.")
            return

        try:
            msg = MIMEMultipart("alternative")
            msg["From"] = sender_email
            msg["To"] = recipient_email
            msg["Subject"] = subject
            msg.attach(MIMEText(plain_text, "plain"))
            msg.attach(MIMEText(html_body, "html"))

            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(sender_email, sender_password)
                server.send_message(msg)

            print(f"Email sent to {recipient_email}")
        except Exception as e:
            print(f"Email error: {e}. Synopsis saved to archive.")

    # ------------------------------------------------------------------
    # Main run
    # ------------------------------------------------------------------

    def run(self, dry_run: bool = False) -> None:
        print("=" * 60)
        print(f"Daily Digest — {self.filter_config.get('digest_name', 'My Digest')}")
        print(f"Running at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        if dry_run:
            print("DRY RUN — email will not be sent")
        print("=" * 60)

        historical = self.get_historical_synopses(days=7)

        meetings: List[Dict] = []
        if self.granola_client:
            meetings = self.granola_client.get_recent_meetings()

        if not meetings:
            print("No Granola meetings found. Make sure Granola is installed and you are signed in.")

        synopsis = self.generate_synopsis(historical, meetings=meetings)
        self.save_synopsis(synopsis)
        self.update_site_data()

        if dry_run:
            print("\n--- DIGEST PREVIEW (email skipped) ---")
            print(synopsis.get("synopsis", ""))
            print("--- END PREVIEW ---\n")
        else:
            self.send_email(synopsis)

        print("=" * 60)
        print("Digest completed successfully")
        print("=" * 60)


def main():
    parser = argparse.ArgumentParser(description="Daily Digest")
    parser.add_argument("--dry-run", action="store_true",
                        help="Generate digest but skip email")
    args = parser.parse_args()

    try:
        DailyDigest().run(dry_run=args.dry_run)
    except Exception as e:
        print(f"Fatal error: {e}")
        raise


if __name__ == "__main__":
    main()
